services:
  keycloak:    
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev
    ports:
      - 8080:8080
    restart: unless-stopped

  kc-django:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    restart: unless-stopped
